version: '3.7'

services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTION_STREAM_NAME=${PREDICTION_STREAM_NAME}
      - RUN_ID=test123
      - MODEL_LOCATION=/app/model
      - KINESIS_ENDPOINT_URL=http://kinesis:4566/
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    volumes:
      - "./model:app/model"
    
  # kinesis:
  #   image: localstack/localstack
  #   ports: 
  #     - "4566:4566"
  #   environment:
  #     - SERVICES=kinesis


