apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db:5432
    database: monitoring
    uers: postgres
    secureJsonData:
      password: 'password'
    jsonData:
      sslmode: 'disable'


