{
 "title": "medium_fare_amt Copy",
 "time": { "from": "2024-02-18T18:41:32.043Z", "to": "2024-04-04T04:54:05.911Z" },
 "panels": [
  {
   "title": "medium_fare amt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select medium_of_fare_amount, \"timestamp\" from metrics "
    }
   ]
  },
  {
   "title": "Top 5 medium fare amt",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"timestamp\", medium_of_fare_amount\nfrom metrics \nwhere \"timestamp\" > '2024-3-1'\nORDER BY medium_of_fare_amount desc\nlimit 5"
    }
   ]
  },
  {
   "title": "medium_trip distance",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \"timestamp\", medium_of_trip_distance\nfrom metrics "
    }
   ]
  }
 ]
}